services:
  api:
    image: datascientest/fastapi:1.0.0
    ports:
      - "8000:8000"
    networks:
      - test_suite
  authentication:
    build:
      dockerfile: ./authentication/Dockerfile
      context: ./authentication/  
    image: authentication
    networks:
      - test_suite
    environment:
      - API_HOST=api
      - LOG=1
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - "api"
  authorization:
    build:
      dockerfile: ./authorization/Dockerfile
      context: ./authorization/ 
    image: authorization
    networks:
      - test_suite
    environment:
      - API_HOST=api
      - LOG=1
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - "api"
  content:
    build:
      dockerfile: ./content/Dockerfile
      context: ./content/
    image: content
    networks:
      - test_suite
    environment:
      - API_HOST=api
      - LOG=1
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - "api"
networks:
  test_suite: